version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atm-api
    restart: always
    env_file:
      - example.env
    ports:
      - "7771:7771"
    environment:
      API_PORT: 7771
# La base de datos debe estar accesible desde el URI en el .env
# No se despliega MySQL aquí, solo la API
